config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'
  resources :departments do
    resources :items
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :departments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  def index
    @departments = Department.all
  end

  def show
    @department = Department.find(params[:id])
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(departments_params)

    if @department.save
      redirect_to departments_path
    else
      render :new
    end

  end

  def edit
    @department = Department.find(params[:id])

    if @department.update(departments_params)
      redirect_to departments_path
    else
      render :edit
    end
  end

  def update
    if @department.update(sub_params)
      redirect_to @department
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private 
  
    def set_sub
      @sub = Sub.find(params[:id])
    end

    def departments_params
      params.require(:department).permit(:title)
    end

end

app/controllers/items_controller.rb
require 'pry'

class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @department.items
  end

  def show
  end

  def new
    binding.pry
    @item = @department.items.new
  end

  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to [@department, @item]
    else
      render :new
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private
    def set_department
      @department = Department.find(params[:department_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/edit.html.erb
<h1>Edit Department</h1>
<%= form_for @department do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1> Departments </h1>
<p><%= link_to 'New Department', new_department_path %></p>
<% @departments.each do |department| %>
  <h2><%= department.title %></h2>
  <%= link_to 'Show Department', department_path(department) %>
  <%= link_to 'Edit Department', edit_department_path(department) %>
<% end %>

app/views/departments/new.html.erb
<h1>New Department</h1>
<%= form_for @department do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/departments/show.html.erb
<h1><%= @department.title %></h1>
<p><%= link_to 'New Item', new_department_item_path(@department) %></p>

<%= link_to 'Back', departments_path %>

app/views/items/index.html.erb
<h1>Click an Item To View Content</h1>
<%= link_to 'Create a new item', new_department_item_path(@department) %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to items.title, [@department, items] %></li>
  <% end %>
</ul>

app/views/items/new.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<%= form_for [@department, @item] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h1><%= @department.title %> - <%= @item.title %></h1>
<%= link_to 'Edit Item', edit_department_item_path([@department, @item]) %>
<%= link_to 'Delete Item', [@department, @item], method: :delete %>
<%= link_to 'Back To Items', department_items_path(@department) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>